name: Python

on: workflow_dispatch

jobs:
  python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)" > ${{ matrix.python-version }}.txt

      - name: Upload math result for job 1
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.python-version }}
          path: ${{ matrix.python-version }}.txt
